### ISSUE TITLE
What are the advantages of docker?

### ISSUE THREAD

**Issue by tdhz77** [kadirahq/meteor-up#125]
If a redeployment fails my app falls back to a working build. Can anybody quickly explain the benefits of docker here. I'm not seeing any difference from my perspective between mup / mupx. Are deployments supposed to be faster? I have not found this to be the case.

In terms of the project is this accurate?

Mup (Deprecated, doesn't work for meteor 1.3) 
Mupx (Somewhat Stable?)
Meteor-up (Beta, will be used in future?)

**Comment by MasterJames** [comment]
Yes that's accurate. 
Docker is worth digging into. Spend a few days to learn it. It's faster to load and better in other ways.
At first seems disconnected and hard to access look at "docker exec" you can execute any script or even bash to gain access from seemingly afar. Typically it's using the volume argument to mount the deployment targets local file system for persistant data.
Learn to love it. It's a way of life for you. Lots of better places to learn "why docker".
